# Generated by Django 3.0.6 on 2020-06-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('PATIENT_DICOM', models.FileField(default='', upload_to='DICOM/')),
                ('MASK_DICOM', models.FileField(default='', upload_to='DICOM/')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Result', models.IntegerField(null=True)),
            ],
        ),
    ]
