# Generated by Django 3.0.6 on 2020-06-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.FileField(default='', upload_to='DICOM/')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
