# Generated by Django 3.0.6 on 2020-06-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_auto_20200616_1858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeepModel',
        ),
    ]
